import { User } from 'src/app/modules/uikit/pages/table/model/user.model';

export const dummyData: User[] = [
  {
    id: 1,
    name: 'Isaac Akonkwa',
    age: 24,
    username: 'akon1703',
    email: 'akonkwaushindi@gmail.com',
    phone: '+243970137369',
    website: 'bio.link/akon1703',
    occupation: 'Web',
    hobbies: ['coding', 'hiking', 'reading'],
    selected: true,
    status: 1,
    created_at: '2025-03-12T12:34:56Z',
  },
  {
    id: 2,
    name: 'Georges Byona',
    age: 12,
    username: 'l0s1ng50n',
    email: 'georgesbyona.com',
    phone: '+243987654321',
    website: 'gdgocucbukavu.vercel.app',
    occupation: 'Flutter',
    hobbies: ['drawing', 'photography', 'travel'],
    selected: false,
    status: 1,
    created_at: '2025-03-14T12:34:56Z',
  },
  {
    id: 3,
    name: 'Marie Reine Bigabwa',
    age: 4,
    username: 'marie.reine',
    email: 'nyotabigabwa@gmail.com',
    phone: '+243987654321',
    website: 'gdgocucbukavu.vercel.app',
    occupation: 'Web',
    hobbies: ['writing', 'yoga', 'baking'],
    selected: true,
    status: 2,
    created_at: '2025-03-16T12:34:56Z',
  },
  {
    id: 4,
    name: 'Imani Bahati',
    age: 28,
    username: 'Dr.Faith',
    email: 'imanibahati.com',
    phone: '+243987654321',
    website: 'gdgocucbukavu.vercel.app',
    occupation: 'AI/ML',
    hobbies: ['data analysis', 'cycling', 'music'],
    selected: false,
    status: 2,
    created_at: '2025-03-18T12:34:56Z',
  },
  {
    id: 5,
    name: 'Kevin Kishikanyi',
    age: 40,
    username: 'kevin.kish',
    email: 'kevin.kishikanyi@gmail.com',
    phone: '+243987654321',
    website: 'gdgocucbukavu.vercel.app',
    occupation: 'Flutter',
    hobbies: ['innovation', 'gaming', 'kop'],
    selected: true,
    status: 1,
    created_at: '2025-03-20T12:34:56Z',
  },
  {
    id: 6,
    name: 'Daniella Zihalirwa',
    age: 32,
    username: 'danzilla',
    email: 'daniella.zihalirwa@gmail.com',
    phone: '+243987654321',
    website: 'gdgocucbukavu.vercel.app',
    occupation: 'Web',
    hobbies: ['design', 'gardening', 'swimming'],
    selected: false,
    status: 1,
    created_at: '2025-03-22T12:34:56Z',
  },
  {
    id: 7,
    name: 'Benedict Lubembela',
    age: 40,
    username: 'ben66',
    email: 'mahangobenedict4@gmail.com',
    phone: '+243987654321',
    website: 'gdgocucbukavu.vercel.app',
    occupation: 'Flutter',
    hobbies: ['innovation', 'gaming', 'kop'],
    selected: true,
    status: 1,
    created_at: '2025-03-20T12:34:56Z',
  },
  {
    id: 8,
    name: 'Christian Aganze',
    age: 32,
    username: 'danzilla',
    email: 'daniella.zihalirwa@gmail.com',
    phone: '+243987654321',
    website: 'gdgocucbukavu.vercel.app',
    occupation: 'Kotlin',
    hobbies: ['app dev', 'learning', 'swimming'],
    selected: false,
    status: 1,
    created_at: '2025-03-22T12:34:56Z',
  }
];
